name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 15, 14, 13, 12, 11, 10]
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      # Install and run postgres
      - run: pg-start ${{ matrix.pg }}

      # Install packages
      - run: mkdir -p /usr/share/man/man1
      - run: apt-get install -yq librdkafka-dev libz-dev default-jre-headless wget

      # Clone repo
      - uses: actions/checkout@v2

      # Install and run zookeeper/kafka
      - run: mkdir /kafka
      - run: ./run_kafka.sh
        working-directory: ./test

      # Build kafka_fdw and run tests
      - run: pg-build-test
        env:
          KAFKA_PRODUCER: "/kafka/bin/kafka-console-producer.sh"
          KAFKA_TOPICS: "/kafka/bin/kafka-topics.sh"
